### PR TITLE
"Stop" -> "Pause" on timer button to reduce confusion

### PR DESCRIPTION
**Pull request by Samathingamajig**
Generally, countdown timers say "pause" to let the user know that it can be resumed later, as "stop" is generally a final action.

Ideally, there would be some kind of state to track "Start" -\> "Pause" \<-\> "Resume", but I didn't want add complexity. If others think this would be good, it's only adding a boolean `useState` and slightly complicating the displaying section with nested ternary.

### CODE REVIEW

**Comment by royanger** [comment]
Hey Sam, can you add your github user name to contributors.yml? Thanks

**Review by royanger — APPROVED** [review]
Great change.

**Comment by Samathingamajig** [comment]
@royanger I've added my name to the contributors list

**Comment by royanger** [comment]
Thanks @Samathingamajig

**Pull request merged**
