### PR TITLE
Fixed bugs from adding Youtube widget

### PR DESCRIPTION
**Pull request by mechakin**
There were some syntax bugs that came from resolving conflicts, should be fixed now

### CODE REVIEW

**Comment by Melkeydev** [comment]
A few comments:
- When a person adds the widget through the widget menu - it is automatically toggled to be on. If we add it, can we it toggled off?
- image
when a user adds the YT widget on the side bar, it doesnt get appended to the end. 
- 
image
I am adding a youtube URL and i pressed enter and I am getting this error
This is because i am using the shorter URL link. When I put the full link it works correctly. Not a blocker.

**Comment by mechakin** [comment]
To answer your comments

- We can make the widget toggle off by default
- Do you want the YT widget to be appended at the end of all the icons?

As for the last comment that is *really* weird i've tested out this video and a couple others with the shortened link and it seemed to work just fine, there might be a weird bug in the regex to validate the link

Screenshot 2023-11-03 at 5 17 27 PM

**Comment by mechakin** [comment]
Took your feedback and made sure to fix the issues you addressed, however I wasn't able to replicate the issue where if the person adds the widget through the widget menu, the widget automatically would be turned on.

That being said:

- The bug with the shortened video link was because of a small issue with the regex where it would cut off the first letter of the URL if it started with a "v". Should all be fixed now.

- The YT widget on the sidebar is now appended at the end.

**Review by Melkeydev — APPROVED** [review]
LGTM

**Pull request merged**
