### PR TITLE
Replace Alert() with toast

### PR DESCRIPTION
**Pull request by justnat3**
Linked to https://github.com/MelkeyOSS/astrostation/issues/248

### CODE REVIEW

**Comment by Melkeydev** [comment]
i think you missed one when clicking CLEAR ALL on tasks.

**Comment by justnat3** [comment]
> i think you missed one when clicking CLEAR ALL on tasks.
> 

Thanks, I will catch that tonight

**Comment by justnat3** [comment]
> i think you missed one when clicking CLEAR ALL on tasks.

That should be a modal. Not within the scope of this PR :)

**Review by Melkeydev — APPROVED** [review]
LGTM

**Pull request merged**
