### PR TITLE
added persistent playlists with a limit of 5 playlists at once

### PR DESCRIPTION
**Pull request by cimok2000**
Added persistent playlists which save to local storage #253 
_The playlists dropdown menu is kinda ugly but I can't design anything 💀_

### CODE REVIEW

**Comment by herropaul** [comment]
Hey, great work on this btw! I do wanna point out tho we may want have a use case to handle duplicate playlists added. This would prevent showing the same playlist added. Thoughts?

**Comment by herropaul** [comment]
Another thing I thought would be cool to see is the name of the playlist being shown on the drop down. I think currently it just shows "Playlist" when a new playlist is added?

**Comment by cimok2000** [comment]
yeah I can look into adding them! I'll look into duplicate playlists and I'll look into getting the name, the only way I can think of doing the name from Spotify is using their API which will require using an API key, I'll look into it, if there's any other way that you know of doing that I'd love to know, thanks!

**Comment by royanger** [comment]
Let's avoid the API for now, though we are starting to spec out a backend and can provide that in the future.

**Comment by Melkeydev** [comment]
@cimok2000 This is a really cool PR.
- As mentioned earlier, since we are not gonna to use the Spotify API just yet (until backend is finished). Do you think you can add a feature that lets users name the playlist just so we can avoid the Playlist generic name?
- Would it make sense to remove possible duplications?

**Comment by cimok2000** [comment]
yeah, I'll make it so duplications are not possible and I'll also make it so that a user can add a unique name for now

**Comment by Melkeydev** [comment]
@cimok2000 Hey! Any update on this beautiful PR?

**Comment by royanger** [comment]
@cimok2000 Could you comment in Issue https://github.com/MelkeyOSS/astrostation/issues/253 so we can assign it to you?

**Review by Melkeydev — APPROVED** [review]
LGTM

**Pull request closed without merging**
