### PR TITLE
Update production

### PR DESCRIPTION
**Pull request by royanger**

### CODE REVIEW

**Review by Melkeydev — COMMENTED** [review]
We should uptick version number in package.json

**Comment by royanger** [comment]
> "We should uptick version number in package.json"

For sure. This can and probably should be done right before merging. IC PRs into staging could be bug fixes, adding functionality or even a major new release so the IC wouldn't be able to reliably update the version number. You, I or in the future other maintainers can just do a quick edit in GitHub to bump the version. I did a minor version bump as there was some minor new stuff added.

**Comment by royanger** [comment]
@eraychumak Can you open up a super quick PR and just update contributors.yml? Thanks!

**Comment by eraychumak** [comment]
> @eraychumak Can you open up a super quick PR and just update contributors.yml? Thanks!

Done, #230  👍

**Comment by royanger** [comment]
Thank you @eraychumak!

**Pull request merged**
